openapi: '3.0.2'
info:
  title: Fabric API 
  version: '1.0'
servers:
  - url: http://localhost:1337

components:
  schemas:
      newInvoice:
        type: object
        properties:
          invoiceno: 
            type: string
          sender:
            type: string
          receiver:
            type: string
          encryptedData:
            type: string
          key:
            type: string
          iv:
            type: string
      listOfInvoices:
        type: array
        items: 
          type: object
          properties:
            Key: 
              type: string
            Record: 
              $ref: '#/components/schemas/invoice' 
      invoice:
        type: object
        properties:
          processor: 
            type: string
          receiver:
            type: string
          sender:
            type: string
          status:
            type: string
      invoiceStatus:
        type: object
        properties:
          status:
            type: string
      privateData:
        type: object
        properties:
          encryptedData:
            type: string
          iv:
            type: string
          key:
            type: string
      invoiceResponse:
        type: object
        properties:
          invoice:
            $ref: '#/components/schemas/invoice' 
          privateData:
            $ref: '#/components/schemas/privateData' 
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

paths:
  /invoices/list:
    get:
      description: get all invoices for the account  
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listOfInvoices' 
        '400':
          description: Processing error
  /invoices/new:        
    post:
      description: add an invoice to the ledger
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newInvoice' 
      responses:
        '200':
          description: OK
        '400':
          description: Processing error

  /invoice/{invoiceId}:
    get:
      description: get an invoice
      parameters:
        - in: path
          name: invoiceId
          schema:
            type: string
          required: true
          description: unique ID of an invoice
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invoiceResponse' 
    post: 
      description: update an invoice
      parameters:
        - in: path
          name: invoiceId
          schema:
            type: string
          required: true
          description: unique ID of an invoice  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/invoiceStatus'
      responses:
        '200':
          description: OK
        '400':
          description: Processing error

    delete:
      description: delete an invoice
      parameters:
        - in: path
          name: invoiceId
          schema:
            type: string
          required: true
          description: unique ID of an invoice  
      responses:
        '200':
          description: OK
        '400':
          description: Processing error

security:
  - basicAuth: []




